### PR TITLE
fix(admin): display parent dealership name

### LINKED ISSUE #115: Remove UUID DLRSHP in Application view
Remove Dlrshp since it's not a unique number anymore. It displays a unique ID is not useful anymore. 

Image

### PR DESCRIPTION
**Pull request by Fenrikur**
closes #115

### CODE REVIEW

File: app/Filament/Resources/ApplicationResource.php [hunk 1]
```diff
@@ -154,18 +154,20 @@ public static function table(Table $table): Table
                         return $record->isReady();
                     })
                     ->boolean(),
-                Tables\Columns\TextColumn::make('dlrshp')
+                Tables\Columns\TextColumn::make('Parent Dealership')
                     ->getStateUsing(function (Application $record) {
-                        return $record->parent_id ?: $record->id;
+                        return ($record->parent()->first()?->getFullName() ?? $record->getFullName());
```
Comment (Diftraku) [inline app/Filament/Resources/ApplicationResource.php:159]: Should this default to an empty value if there is no parent dealership relation?

Comment (Fenrikur) [reply app/Filament/Resources/ApplicationResource.php:159]: No, this is on purpose, because sorting by this field would otherwise no longer visually group shares/assistants with their parents. Since sorting and display values are actually separated though, we could consider it.
In the end probably a question for @Corborax? (:

**Review by SharkyTheWhite — APPROVED** [review]
Seems to work, nice to have feature!

File: app/Filament/Resources/ApplicationResource.php (hunk 1 above)
Comment (SharkyTheWhite) [reply app/Filament/Resources/ApplicationResource.php:159]: You could argue that a dealer who has no parent is the main dealer in their own dealership so I think this can be just kept this way. The mentioned impact on sorting by this column is a valid point I think.

Comment (Diftraku) [reply app/Filament/Resources/ApplicationResource.php:159]: Both ways work and we can default to empty value later on if there's any confusion.

**Comment by Diftraku** [comment]
LGTM, didn't see anything scary pop out to me :3
